# Three Methods are there to fill values in pandas Data Frame

## 1: fillna() method: It fill Nan values to given values.
## 2: interpolate() method: It first guess the values and then fills the correct guessed values in          place of Nan or missing values (integer values only).

In [1]:
from pandas import *

In [3]:
df=read_csv("E:\Records2.csv")
df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.7
2,Europe,Russia,Office Supplies,Offline,L,05-02-2014,341417157,05-08-2014,1779,Invalid
3,Sub-Saharan Africa,Sao Tome and Principe,NaN,Online,C,6/20/2014,514321792,07-05-2014,8102,Invalid
4,Sub-Saharan Africa,Rwanda,NaN,Offline,L,02-01-2013,115456712,02-06-2013,5062,Invalid
5,Australia and Oceania,Solomon Islands,NaN,Online,C,02-04-2015,547995746,2/21/2015,2974,Invalid
6,Sub-Saharan Africa,Angola,NaN,Offline,M,4/23/2011,135425221,4/27/2011,4187,Invalid
7,Sub-Saharan Africa,Burkina Faso,NaN,Online,H,7/17/2012,871543967,7/27/2012,8082,Invalid
8,Sub-Saharan Africa,Republic of the Congo,Personal Care,Offline,M,7/14/2015,770463311,8/25/2015,6070,81.73
9,Sub-Saharan Africa,Senegal,Cereal,Online,H,4/18/2014,616607081,5/30/2014,6593,205.7
10,Asia,Kyrgyzstan,Vegetables,Online,H,6/24/2011,814711606,07-12-2011,124,154.06
11,Sub-Saharan Africa,Cape Verde,Clothes,Offline,H,08-02-2014,939825713,8/19/2014,4168,109.28
12,Asia,Bangladesh,Clothes,Online,L,1/13/2017,187310731,03-01-2017,8263,109.28
13,Central America and the Caribbean,Honduras,Household,Offline,H,02-08-2017,522840487,2/13/2017,8974,668.27

## fillna() method

In [4]:
df.fillna()

ValueError: Must specify a fill 'value' or 'method'.